# Generated by Django 3.0.7 on 2020-06-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200606_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pic',
            new_name='img',
        ),
    ]
