# Generated by Django 3.0.7 on 2020-06-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200606_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='user_image'),
        ),
    ]
