# Generated by Django 3.0.7 on 2020-06-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200607_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
