# Generated by Django 3.0.7 on 2020-06-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200607_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='user_image'),
        ),
    ]
