# Generated by Django 3.0.7 on 2020-06-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customer_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerImage',
        ),
    ]
