# Generated by Django 3.0.7 on 2020-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200609_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img',
            field=models.ImageField(default='default.png', upload_to='user_image'),
        ),
    ]
