# Generated by Django 3.0.7 on 2020-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200609_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media/user_image'),
        ),
    ]
