# Generated by Django 3.0.7 on 2020-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
