# Generated by Django 3.0.7 on 2020-07-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200714_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_name',
        ),
    ]
