# Generated by Django 3.0.7 on 2020-07-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200714_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_name',
            new_name='title',
        ),
    ]
