# Generated by Django 3.0.7 on 2020-07-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Главная', 'Главная страница'), ('Специализция', 'Страница специализации')], default='Главная', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, max_length=1000)),
                ('text_second', models.TextField(blank=True, db_index=True, max_length=1000)),
                ('text_third', models.TextField(blank=True, db_index=True, max_length=1000)),
                ('text_four', models.TextField(blank=True, db_index=True, max_length=1000)),
                ('title_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='main.Post_Category')),
            ],
        ),
    ]
