# Generated by Django 3.0.7 on 2020-07-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.Post_Category'),
        ),
    ]
