# Generated by Django 3.0.7 on 2020-07-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200716_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.Post_Category'),
        ),
    ]
