# Generated by Django 3.0.7 on 2020-07-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200716_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_one',
        ),
    ]
