# Generated by Django 3.0.7 on 2020-07-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200719_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_four',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_one',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_second',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_third',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
