# Generated by Django 3.0.7 on 2020-07-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200720_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_second',
        ),
        migrations.CreateModel(
            name='Post_second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_second', models.TextField(blank=True, db_index=True, max_length=1000, null=True)),
                ('title_nam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_second', to='main.Post_Category')),
            ],
        ),
    ]
