# Generated by Django 3.0.7 on 2020-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200720_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_second',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_name',
        ),
        migrations.AddField(
            model_name='post',
            name='title_name',
            field=models.ManyToManyField(related_name='post', to='main.Post_Category'),
        ),
        migrations.DeleteModel(
            name='Post_second',
        ),
    ]
