# Generated by Django 3.0.7 on 2020-07-29 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200720_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_four',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_one',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_second',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_third',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True),
        ),
    ]
